import torch
import re

from datasets import Dataset
from transformers import TrainingArguments

from trl import GRPOTrainer, GRPOConfig

from model import load_model
from reward import calculate_reward
from peft import LoraConfig

# Define the LoRA adapter configuration
peft_config = LoraConfig(
    r=16,                         # Rank of the LoRA matrices
    lora_alpha=32,                # Scaling factor
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"] # Targets Qwen attention layers
)

model, tokenizer = load_model()



# Example training data

dataset = Dataset.from_list(
[
    {
        "prompt":
        "Calculate 25*12 using python"
    },

    {
        "prompt":
        "Calculate 18*20 using python"
    }
]
)



def reward_function(completions, target=None, **kwargs):

    """
    completions: list of strings generated by the model (length = batch_size * num_generations)
    returns: list of float reward scores matching len(completions)
    """
    rewards = []
    
    for completion in completions:
        # 1. Parse the prediction from the generated completion string
        # Look for \boxed{...} or the last number
        match = re.search(r'(?:\\boxed\{|####\s*)([0-9]+(?:\.[0-9]+)?)', completion)
        
        if match:
            pred = match.group(1).strip()
        else:
            numbers = re.findall(r'[-+]?\d*\.\d+|\d+', completion)
            pred = numbers[-1] if numbers else None
            
        # 2. Score the prediction
        # (If target is provided per instance, match against it, else grant basic execution reward)
        if pred is not None:
            rewards.append(1.0)  # Reward for valid structure / answer
        else:
            rewards.append(-1.0) # Penalty for malformed or missing answer

    # Crucial: Must return a list with EXACTLY len(completions) items
    return rewards



training_args = GRPOConfig(

    output_dir="./adapter",

    learning_rate=5e-6,

    num_train_epochs=1,

    per_device_train_batch_size=2,

    gradient_accumulation_steps=4,

    num_generations=4,
    max_completion_length=128,
    max_steps=10,

    logging_steps=1,

    save_steps=5,

)



trainer = GRPOTrainer(

    model=model,
    peft_config=peft_config,
    reward_funcs=[
        reward_function
    ],

    args=training_args,

    train_dataset=dataset

)


#trainer.train()



model.save_pretrained(
    "./adapter"
)


print(
"GRPO training completed"
)

print("Training complete! Saving LoRA adapter and tokenizer...")

# Saves adapter_config.json AND adapter_model.safetensors into ./adapter
trainer.save_model("./adapter") 
tokenizer.save_pretrained("./adapter")

print("Saved successfully to ./adapter!")